
name: PullRequest - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch

  pull_request:
    branches: [ main ]

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
        with:
          command: branch ="${{ github.head_ref }}", diffGitHub_pullrequest(branch)
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: ${{ github.workspace }}\*.html
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v1
        with:
          command: runtests

#   Copyright 2022 The MathWorks, Inc.
