
name: PushToMain - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
 
 push:
    branches: [ main ]

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Start Display Server
        run: |
         sudo apt-get install -y xvfb
         Xvfb :99 &
         export DISPLAY=:99
         echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v2
        with:
          command: lastpush="${{ github.event.before }}", diffGitHub_push(lastpush)
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v4
        with:
           name: diffreports
           path: ${{ github.workspace }}/*.html
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v2
        with:
          command: runtests

#   Copyright 2022-2024 The MathWorks, Inc.
